### ISSUE TITLE
vsam APIs could not operate the data set which is being viewed by others

### ISSUE THREAD

**Issue by tangthth** [ibmruntimes/vsam.js#5]
### **Issue Description:**
when the data set is being viewed by others, VSAM APIs could not operate the data set: 
- vsam.exist(dsname) returns false even if it exists
- vsam.openSync() could not open the data set and reports error message "TypeError: Invalid dataset name", which is misleading to user

### **Reproduce Steps:**
1. prepare a vsam data set, view the data set in terminal 1 and keep the view mode not exited
2. write nodejs script 1 to judge if the vsam data set exists or not, execute script 1 in terminal 2
3. write nodejs script 2 to open the vsam data set, execute script 2 in terminal 2

### **Logs:**
For Step 2:
        vsamObj = vsam.allocSync(dsname, JSON.parse(fs.readFileSync('schema.json
')))                                                                            
                       ¬                                                                                                                                       
TypeError: Invalid dataset format                                               
    at TypeError (native)                                                       
    at vsamOpen (/u/usra/workdir/nodejs/nodejs.test.vsam_1.0.0/sc
ripts/test_vsam.js:25:17)                                                       
    at Object.<anonymous> (/u/usra/workdir/nodejs/nodejs.test.vsa
m_1.0.0/scripts/test_vsam.js:160:1)                                             
    at Module._compile (module.js:577:32)                                       
    at Object.Module._extensions..js (module.js:586:10)                         
    at Module.load (module.js:494:32)                                           
    at tryModuleLoad (module.js:453:12)                                         
    at Function.Module._load (module.js:445:3)                                  
    at Module.runMain (module.js:611:10)                                        
    at run (bootstrap_node.js:394:7)

For Step 3:
/u/usra/workdir/nodejs/nodejs.test.vsam_1.0.0/scripts/test_vsam.j
s:21                                                                            
        vsamObj = vsam.openSync(dsname, JSON.parse(fs.readFileSync('schema.json'
)))                                                                             
                       ¬                                                                                                                                        
TypeError: Invalid dataset name                                                 
    at TypeError (native)                                                       
    at vsamOpen (/u/usra/workdir/nodejs/nodejs.test.vsam_1.0.0/sc
ripts/test_vsam.js:21:17)                                                       
    at Object.<anonymous> (/u/usra/workdir/nodejs/nodejs.test.vsa
m_1.0.0/scripts/test_vsam.js:160:1)                                             
    at Module._compile (module.js:577:32)                                       
    at Object.Module._extensions..js (module.js:586:10)                         
    at Module.load (module.js:494:32)                                           
    at tryModuleLoad (module.js:453:12)                                         
    at Function.Module._load (module.js:445:3)                                  
    at Module.runMain (module.js:611:10)                                        
    at run (bootstrap_node.js:394:7) 

### **Reference:**
Script 1:
```
if (vsam.exist(dsname)) {
	vsamObj = vsam.openSync(dsname, JSON.parse(fs.readFileSync('schema.json')))
	console.log("Open the vsam dataset: " + dsname)
}
else {
	vsamObj = vsam.allocSync(dsname, JSON.parse(fs.readFileSync('schema.json')))
	console.log("New vsam dataset allocated: " + dsname)
}
```

Script 2:
```
	vsamObj = vsam.openSync(dsname, JSON.parse(fs.readFileSync('schema.json')))
	console.log("Open the vsam dataset: " + dsname)
```

**Comment by gabylb** [comment]
This has been fixed in vsam.js v3.0.0, in which a new optional open-mode argument was added to `openSync()`; to open the dataset in read-only mode, pass `"rb,type=record"`. With this, you should be able to have the same dataset opened in read-only mode by more than one process. See also https://github.com/ibmruntimes/vsam.js#open-a-vsam-dataset.
